# 网站基本信息
title: Tech Blog & Projects
tagline: Sharing Knowledge & Showcasing Projects
description: A personal blog about technology, programming, and project showcases
url: 'https://wasd845.github.io'
author: WASD845
avatar: assets/img/avatar.jpg
social:
  name: WASD845
  email: your-email@example.com
  github: wasd845
  # Add more social links if needed
  # twitter: your-twitter
  # linkedin: your-linkedin

# 主题设置
theme_mode: light
toc: true
comments:
  active: giscus
  giscus:
    repo: wasd845/wasd845.github.io    # 替换为您的仓库名
    repo_id: YOUR_REPO_ID              # 从 giscus.app 获取
    category: Announcements
    category_id: YOUR_CATEGORY_ID      # 从 giscus.app 获取
    mapping: pathname
    input_position: bottom
    lang: zh-CN
    reactions_enabled: 1

# 分页设置
paginate: 10

# 语言设置
lang: zh-CN